name: MP Backend Continuous Integration

on:
  # Allows run on-demand
  workflow_dispatch:
    # Runs on `pull_requests` against the `main` branch
    pull_request:
      branches:
        - main
      paths:
        # only when code in the backend application changes
        - "backend/**"
env:
  PYTHON_VERSION: 3.10

jobs:
  # Runs the following jobs: `lint`, `test`
  lint:
    name: MP Backend Lint run
    runs-on:  ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      
      - name: App dependencies caching
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: pipenv-${{ runner.os }}-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            pipenv-${{ runner.os }}-
      
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Pipenv installation
        run: |
          pip install pipenv

      - name: Dependencies installation
        run: |
          pipenv install && pip install flake8
      
      - name: Lint run
        run: |
          pipenv run lint

  test:
    name: MP Backend Tests run
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Pipenv installation
        run: |
          pip install pipenv
      
      - name: Dependencies installation
        run: |
          pipenv install

      - name: Tests run
        run: |
          npm run test

  build:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: [lint, test]
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Pipenv installation
        run: |
          pip install pipenv

      - name: Dependencies installation
        run: |
          pipenv install

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"
      
      - name: Build docker image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_FRONTEND_REPOSITORY_NAME }}:latest .
          docker images

      - name: Cache docker image
        uses: actions/cache@v3
        with:
          path: ~/docker-cache
          key: docker-${{ github.sha }}-backend
          restore-keys: |
            docker-${{ github.sha }}-
