name: MP Frontend Continuous Deployment

on:
  # Allows run on-demand
  workflow_dispatch:
    # Runs on `push` against the `main` branch
    push:
      branches		:
        - main
      paths:
        # only when code in the frontend application changes
        - "frontend/**"
env:
  NODE_VERSION: 18.x

jobs:
  # Runs the following jobs in parallel: `lint`, `test`
  lint:
    name: MP Frontend Lint run
    runs-on:  ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      
      - name: Nodejs dependencies caching
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            npm-
      
      - name: Dependencies installation
        run: |
          npm install
      
      - name: ESLint run
        run: |
          npm run lint -- --fix

  test:
    name: MP Frontend Tests run
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
    
      - name: Dependencies installation
        run: |
          npm install -f
    
    - name: Tests run
      run: |
        npm run test
  
  build:
    name: Build and Push docker image to Amazon ECR
    runs-on: ubuntu-latest
    needs: [lint, test]
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Code checkout
        uses: action/checkout@v3
      
      - name: Dependencies installation
        run: |
          npm install
      
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"
      
      - name: Build docker image
        run: |
          aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
          export EXTERNAL_IP=$(kubectl get svc backend -o=jsonpath='{.status.loadBalancer.ingress[0].hostname}{"\n"}{.status.loadBalancer.ingress[0].ip}')
          echo $EXTERNAL_IP
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_FRONTEND_REPOSITORY_NAME }}:latest --build-arg=REACT_APP_MOVIE_API_URL=http://$EXTERNAL_IP .

      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_FRONTEND_REPOSITORY_NAME }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_FRONTEND_REPOSITORY_NAME }}:${GITHUB_SHA}

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_FRONTEND_REPOSITORY_NAME }}:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_FRONTEND_REPOSITORY_NAME }}:${GITHUB_SHA}
  deploy:
    name: Deploy to K8s
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"
      
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
      
      - name: Run init
        working-directory: ./setup
        run: |
          ./init.sh || true
      
      - name: Update Kustomize image
        working-directory: ./frontend/k8s
        run: |
          kustomize edit set image frontend=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_FRONTEND_REPOSITORY_NAME }}:${GITHUB_SHA}

      - name: Apply K8s resources
        working-directory: ./frontend/k8s
        run: |
          kustomize build | kubectl apply -f -
